# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorta', '0003_auto_20160419_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls_list',
            old_name='url_entry',
            new_name='url',
        ),
    ]
